M48
; DRILL file {KiCad 5.99.0-unknown-6001ac0704~131~ubuntu20.04.1} date Sun Jul 18 17:15:56 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-07-18T17:15:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-6001ac0704~131~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X3.556Y3.556
X45.72Y34.544
T0
M30
